# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapbiomasfogoDialog
                                 A QGIS plugin
 Este plugin permite acesso aos produtos de fogo do Mapbiomas diretamente no Qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-05
        git sha              : $Format:%H$
        copyright            : (C) 2025 by IPAM Amazonia
        email                : contato@mapbiomas.org
 ***************************************************************************/
          ESTE ARQUIVO DEFINI OS PARAMETROS BASICO DO PLUGIN
/***************************************************************************
"""
#Parametros do plugin MapBiomas Fogo
ano_maximo = 2024
ano_minimo = 1985
collection = 4